#Import the base docker image built on top of Alpine
FROM alpine:3.18.3

# ADD ./alpine-mirrors /etc/apk/repositories

WORKDIR /opt/bin

#Add Packages
RUN apk add --no-cache bash sed grep curl coreutils nodejs npm ca-certificates make openssh-client git socat skopeo openssl jq && \
    curl -fSL "https://github.com/genuinetools/img/releases/download/v0.5.11/img-linux-amd64" -o "/opt/bin/img" && chmod a+x "/opt/bin/img" && \
    apk --no-cache add curl-dev wget openjdk8 openjdk11 openjdk17 maven gradle
    

WORKDIR /cli
ADD ./package.json ./package-lock.json ./.npmrc ./
ADD ./scripts ./scripts
ADD ./commands ./commands
RUN npm install --production

ENTRYPOINT [ "npm", "start" ]
