FROM ubuntu:22.04

# Set the SHELL to bash with pipefail option
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Prevent dialog during apt install
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS="yes"

#Add Packages
RUN apt-get -y update && apt-get --no-install-recommends -y install bash sed grep curl coreutils ca-certificates maven gradle openjdk-8-jdk openjdk-11-jdk openjdk-17-jdk

# Install nodejs 16
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash && \
    source ~/.nvm/nvm.sh && \
    nvm install v10 && \
    nvm use v10 && \
    ln -s "$(which node)" /usr/bin/node &&  ln -s "$(which npm)" /usr/bin/npm

WORKDIR /cli
ADD ./package.json ./package-lock.json ./.npmrc ./
ADD ./scripts ./scripts
ADD ./commands ./commands
RUN npm install --production

ENTRYPOINT [ "npm", "start" ]