FROM node:18-alpine3.19

ADD ./alpine-mirrors /etc/apk/repositories

WORKDIR /opt/bin

#Add Packages
RUN apk add --no-cache bash sed coreutils ca-certificates curl-dev wget openjdk8 && \
    apk add --no-cache openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community && \
    wget -O /tmp/openjdk17.tar.gz https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jdk_x64_alpine-linux_hotspot_17.0.5_8.tar.gz && \
    mkdir -p /usr/lib/jvm/java-17-openjdk && tar --extract --file /tmp/openjdk17.tar.gz --directory /usr/lib/jvm/java-17-openjdk --strip-components 1 --no-same-owner && \
    rm /tmp/openjdk17.tar.gz

WORKDIR /cli
ADD ./package.json ./package-lock.json ./.npmrc ./
ADD ./scripts ./scripts
ADD ./commands ./commands
RUN npm install --production

ENTRYPOINT [ "npm", "start" ]
