FROM alpine:3.19.1

# ADD ./alpine-mirrors /etc/apk/repositories

WORKDIR /opt/bin

#Add Packages
RUN apk update && apk add --no-cache bash sed grep curl wget nodejs npm ca-certificates openjdk8 openjdk11 openjdk17

WORKDIR /cli
ADD ./package.json ./package-lock.json ./.npmrc ./
ADD ./scripts ./scripts
ADD ./commands ./commands
RUN npm install --production

ENTRYPOINT [ "npm", "start" ]
