# Get 'yq' from the source
FROM mikefarah/yq:4.6.1 as yq

#Import the base docker image built on top of Alpine
FROM alpine:3.17.3

ADD ./alpine-mirrors /etc/apk/repositories

COPY --from=yq /usr/bin/yq /usr/bin/yq

WORKDIR /opt/bin

#Add Packages
RUN apk add --no-cache bash sed grep curl coreutils nodejs npm ca-certificates make openssh-client git socat skopeo openssl jq && \
    curl -fSL "https://github.com/genuinetools/img/releases/download/v0.5.10/img-linux-amd64" -o "/opt/bin/img" && chmod a+x "/opt/bin/img"

WORKDIR /cli
ADD ./package.json ./package-lock.json ./.npmrc ./
ADD ./scripts ./scripts
ADD ./commands ./commands
ADD ./props /props
RUN npm install --production

ENTRYPOINT [ "npm", "start" ]
