apiVersion: apps/v1
kind: Deployment
metadata:
  name: @process/org@-@process/component.name@
  namespace: @deploy.kube.namespace@
  annotations:
    platform: boomerang
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      org: @process/org@
      component: @process/component.name@
      env: @system/stage.name@
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        org: @process/org@
        component: @process/component.name@
        env: @system/stage.name@
    spec:
      containers:
        - image: @global/container.registry.host@:@global/container.registry.port@/@process/org@/@process/docker.image.name@:@version.name@
          imagePullPolicy: Always
          name: cntr
          ports:
            - name: port-cntr
              containerPort: @process/container.port@
              protocol: TCP
          env:
            - name: DEPLOY_TARGET
              value: "@system/stage.name@"
      imagePullSecrets:
        - name: boomerang.registrykey
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: @process/org@-@process/component.name@
  namespace: @deploy.kube.namespace@
spec:
  ports:
    - name: port-svc
      port: @process/service.port@
      protocol: TCP
      targetPort: port-cntr
  selector:
    org: @process/org@
    component: @process/component.name@
    env: @system/stage.name@
  sessionAffinity: None
